<?php
require_once __DIR__ . '/_shell.php';
requireAdmin();
require_once __DIR__ . '/../../helpers/lead-magnet.php';
require_once __DIR__ . '/../../helpers/email-sequence.php';
require_once __DIR__ . '/../../helpers/mailketing.php';
$process = null;
if ($_SERVER['REQUEST_METHOD'] === 'GET') scribeKickEmailAutomation(); // proses antrean setelah respons (non-blokir)
$pdo = getDB();
$editId = (int) ($_GET['id'] ?? 0);
$edit = null; if ($editId > 0) { $st = $pdo->prepare('SELECT * FROM email_sequences WHERE id=? LIMIT 1'); $st->execute([$editId]); $edit = $st->fetch() ?: null; }
$seqs = $pdo->query("SELECT es.*, lm.title AS lead_magnet_title, (SELECT COUNT(*) FROM email_sequence_steps st WHERE st.sequence_id=es.id) AS step_count, (SELECT COUNT(*) FROM email_sequence_enrollments en WHERE en.sequence_id=es.id AND en.status='active') AS active_count FROM email_sequences es LEFT JOIN lead_magnets lm ON lm.id=es.lead_magnet_id ORDER BY es.updated_at DESC, es.id DESC")->fetchAll();
$magnets = $pdo->query("SELECT id,title FROM lead_magnets ORDER BY title ASC")->fetchAll();
admin_shell_top('Email Sequence', '/admin/email-sequences');
?>
<div class="max-w-6xl space-y-4">
  <div class="flex flex-wrap items-end justify-between gap-3"><div><h1 class="font-display font-semibold text-xl">Email Sequence</h1><p class="text-sm text-gray-500 dark:text-gray-400 mt-1">Atur email terjadwal untuk subscriber baru. HTML email didukung penuh.</p></div><form method="post" action="<?= e(url('/actions/admin/process-email-sequences')) ?>" class="inline"><?= csrfField() ?><button class="inline-flex items-center gap-1.5 rounded-md px-3 py-2 text-sm font-semibold border border-gray-300 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-800"><?= icon('refresh-cw', 'w-4 h-4') ?> Proses antrean</button></form></div>
  <?php if ($process): ?><p class="text-xs text-gray-500">Antrean diperiksa: <?= (int) $process['processed'] ?>, terkirim: <?= (int) $process['sent'] ?>, gagal: <?= (int) $process['failed'] ?>.</p><?php endif; ?>
  <div class="grid lg:grid-cols-[1fr_340px] gap-4">
    <div class="rounded-lg border border-gray-200 dark:border-gray-800 bg-white dark:bg-gray-900 overflow-hidden"><div class="px-5 py-4 border-b border-gray-200 dark:border-gray-800"><h2 class="font-display font-semibold">Sequence aktif &amp; draft</h2></div><div class="divide-y divide-gray-200 dark:divide-gray-800"><?php foreach ($seqs as $s): ?><div class="px-5 py-4 flex items-start justify-between gap-3"><div class="min-w-0"><a href="<?= e(url('/admin/email-sequences?id=' . (int) $s['id'])) ?>" class="font-semibold text-sm hover:text-accent"><?= e($s['name']) ?></a><p class="text-xs text-gray-500 mt-1"><?= e($s['lead_magnet_title'] ?: 'Semua lead magnet') ?> · <?= (int) $s['step_count'] ?> step · <?= (int) $s['active_count'] ?> enrollment aktif</p></div><div class="flex flex-wrap items-center justify-end gap-2 shrink-0"><span class="text-xs <?= $s['status'] === 'active' ? 'text-emerald-600' : 'text-gray-500' ?>"><?= $s['status'] === 'active' ? 'Aktif' : 'Draft' ?></span><a href="<?= e(url('/admin/email-sequences?id=' . (int) $s['id'])) ?>" class="inline-flex items-center gap-1 text-xs font-medium text-accent"><?= icon('pen-line', 'w-3.5 h-3.5') ?> Edit</a><a href="<?= e(url('/admin/email-sequence-steps?id=' . (int) $s['id'])) ?>" class="text-xs font-semibold text-accent">Kelola step</a><form method="post" action="<?= e(url('/actions/admin/delete-email-sequence')) ?>" data-confirm="Hapus sequence ini? Semua step, enrollment, dan antrean email sequence akan ikut dihapus." data-confirm-danger data-confirm-title="Hapus email sequence"><?= csrfField() ?><input type="hidden" name="id" value="<?= (int) $s['id'] ?>"><button type="submit" class="inline-flex items-center gap-1 text-xs font-medium text-red-600"><?= icon('trash', 'w-3.5 h-3.5') ?> Hapus</button></form></div></div><?php endforeach; ?><?php if (!$seqs): ?><div class="p-8 text-center text-sm text-gray-500">Belum ada sequence.</div><?php endif; ?></div></div>
    <form method="post" action="<?= e(url('/actions/admin/save-email-sequence')) ?>" class="rounded-lg border border-gray-200 dark:border-gray-800 bg-white dark:bg-gray-900 p-5 space-y-3"><input type="hidden" name="id" value="<?= (int) ($edit['id'] ?? 0) ?>"><?= csrfField() ?><h2 class="font-display font-semibold"><?= $edit ? 'Edit sequence' : 'Buat sequence' ?></h2><div><label class="block text-xs font-medium mb-1">Nama sequence</label><input name="name" required maxlength="160" value="<?= e($edit['name'] ?? '') ?>" class="w-full rounded-md border border-gray-300 dark:border-gray-700 bg-transparent px-3 py-2 text-sm"></div><div><label class="block text-xs font-medium mb-1">Trigger</label><select disabled class="w-full rounded-md border border-gray-300 dark:border-gray-700 bg-gray-100 dark:bg-gray-800 px-3 py-2 text-sm"><option>Subscriber baru masuk</option></select><input type="hidden" name="trigger_event" value="subscriber_created"></div><div><label class="block text-xs font-medium mb-1">Khusus lead magnet</label><select name="lead_magnet_id" class="w-full rounded-md border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2 text-sm"><option value="0">Semua lead magnet / newsletter</option><?php foreach ($magnets as $m): ?><option value="<?= (int) $m['id'] ?>" <?= (int) ($edit['lead_magnet_id'] ?? 0) === (int) $m['id'] ? 'selected' : '' ?>><?= e($m['title']) ?></option><?php endforeach; ?></select></div><div><label class="block text-xs font-medium mb-1">Status</label><select name="status" class="w-full rounded-md border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2 text-sm"><option value="inactive" <?= ($edit['status'] ?? 'inactive') === 'inactive' ? 'selected' : '' ?>>Draft / nonaktif</option><option value="active" <?= ($edit['status'] ?? '') === 'active' ? 'selected' : '' ?>>Aktif</option></select></div><button class="w-full rounded-md px-4 py-2 text-sm font-semibold text-white" style="background:var(--accent)">Simpan Sequence</button></form>
  </div>
</div>
<?php admin_shell_bottom(); ?>
