expose_php=Off
display_errors=Off
log_errors=On
error_log=/proc/self/fd/2
upload_max_filesize=20M
post_max_size=24M
memory_limit=256M
max_execution_time=120
date.timezone=Asia/Jakarta
session.save_path=/var/lib/php/sessions
session.use_strict_mode=1
session.cookie_httponly=1
session.cookie_samesite=Lax
